name: formletics
description: Flutter Mobx Dio Boilerplate

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  chewie: ^0.9.10
  video_player: ^0.10.8+1
  image_picker: ^0.6.7+17
  multi_image_picker: ^4.6.7
  bubble: ^1.1.8
  flutter_countdown_timer: ^2.0.1
  carousel_slider: ^2.3.2
  http: ^0.12.2
  charts_flutter: ^0.9.0
  rename: ^1.1.9

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main


  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^4.3.2

  # Service locator
  get_it: ^4.0.0
  injectable: ^0.3.0

  # data channel
  data_channel: ^1.0.4+1

  # API fetching
  dio: ^3.0.10
  pretty_dio_logger: ^1.1.1

  # Connectivity
  data_connection_checker: ^0.3.4

  # Local cache
  shared_preferences: ^0.5.6

  meta: ^1.1.8

  # Logging
  logger: ^0.8.3

  # Routing
  auto_route: ^0.6.7

  # Json
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1

  # snackbar
  flushbar:
    git:
      url: https://github.com/AndreHaueisen/flushbar.git
  flash: ^1.2.3

  after_layout: ^1.0.7+2

  equatable: ^1.1.1


  # video player
  # chewie: ^0.9.10
  # video_player: ^0.10.8+1

  # GetFlutter/GetWidget UI Kit Library
  getwidget: ^1.1.3

  # Network Image Libary for caching
  cached_network_image: ^2.2.0+1

  # Retrofit for creating api url source
  retrofit: ^1.3.4

  font_awesome_flutter: ^8.8.1

  flutter_svg:
    # git:
    #   url: git://github.com/gskinnerTeam/flutter_svg.git
    #   ref: 12b55b464d2e253f411a17798527a7daa2c00ceb

  loadany: ^0.1.4

  cached_video_player: ^1.0.3

  stop_watch_timer: ^0.6.0+1

  screen: ^0.0.5

  searchable_dropdown: ^1.1.3

  webview_flutter: ^1.0.7
  

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

  # Linting
  lint: ^1.1.1

  # Build runner
  build_runner:

  # Service locator
  injectable_generator:

  # MobX
  mobx_codegen: ^1.1.0+1 

  # Routing
  auto_route_generator: ^0.6.8

  # Retrofit
  retrofit_generator: ^1.3.7+5

  # Datetime Picker
  flutter_datetime_picker: ^1.4.0
  

flutter_icons:
  image_path: "assets/images/new-logo.jpg"
  android: true
  ios: true
  macos: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/powered_by.png
    - assets/images/login-bg-bl.jpg
    - assets/svg/muscle.svg
    - assets/images/3.png
   
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #    - family: ProductSans
  #      fonts:
  #        - asset: assets/fonts/Product-Sans-Regular.ttf
  #        - asset: assets/fonts/Product-Sans-Italic.ttf
  #          style: italic
  #        - asset: assets/fonts/Product-Sans-Bold.ttf
  #          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages